/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // Styled as a category head without being one. Docusaurus normalizes a category with no items
    // back into a plain doc link, so the category look comes from `sidebar-section-head` in
    // custom.css instead. It has no children and must not appear to.
    { type: "doc", id: "intro", className: "sidebar-section-head" },
    {
      type: "category",
      label: "LFSM",
      link: { type: "doc", id: "tutorial-basics/lfsm" },
      items: [
        { type: "doc", id: "tutorial-basics/rollups" },
        { type: "doc", id: "tutorial-basics/NISPs" },
        { type: "doc", id: "tutorial-basics/emissions" },
      ],
    },
    // No link: there is no mining overview page for this category to open.
    {
      type: "category",
      label: "Mining",
      items: [
        { type: "doc", id: "tutorial-basics/mining-on-lithos" },
        { type: "doc", id: "tutorial-basics/candidate-building" },
        { type: "doc", id: "tutorial-basics/voting" },
      ],
    },
    {
      type: "category",
      label: "LithosDex",
      link: { type: "doc", id: "lithosdex/overview" },
      items: [
        { type: "doc", id: "lithosdex/orders" },
        { type: "doc", id: "lithosdex/liquidity" },
      ],
    },
  ],
  openApiSidebar: [
    {
      type: "category",
      label: "Lithos API",
      link: {
        type: "generated-index",
        title: "Lithos API",
        description:
          "Overview of the Lithos Client API. Lithos provides API calls to view information about mined blocks, miner reward payments, stratum parameters, and collateral utxos. Additionally, authentication allows for miners to create" +
          " collateral UTXOs which are crucial to continue mining on Lithos. In order to try out API calls, click on a specific request and use the bottom right panel to interact with the client.",
        slug: "/category/lithos-api"
      },
      items: require("./docs/lithosapi/sidebar.js")
    }
  ],
  // Both categories are declared rather than autogenerated. `autogenerated` pointed at a directory
  // emits that directory's contents flat and ignores its `_category_.json`, so it cannot produce a
  // collapsible category. Adding a page to either one means adding a line here.
  startUpSidebar: [
    {
      type: "category",
      label: "Startup guide",
      link: { type: "doc", id: "startup-intro" },
      items: [
        { type: "doc", id: "startup/testnet-node" },
      ],
    },
    {
      type: "category",
      label: "Configuration",
      link: { type: "doc", id: "configuration/overview" },
      items: [
        { type: "doc", id: "configuration/node" },
        { type: "doc", id: "configuration/stratum" },
        { type: "doc", id: "configuration/candidate" },
        { type: "doc", id: "configuration/batching" },
        { type: "doc", id: "configuration/emission" },
        { type: "doc", id: "configuration/wallet" },
        { type: "doc", id: "configuration/stats" },
        { type: "doc", id: "configuration/sync" },
        { type: "doc", id: "configuration/runtime" },
      ],
    },
    {
      type: "category",
      label: "Operations",
      items: [
        { type: "doc", id: "operations/failure-modes" },
        { type: "doc", id: "operations/reporting-issues" },
      ],
    },
  ],
};

export default sidebars;