/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: "doc", id: "intro"},
    { type: "autogenerated", dirName: "tutorial-basics" }
  ],
  openApiSidebar: [
    {
      type: "category",
      label: "Lithos API",
      link: {
        type: "generated-index",
        title: "Lithos API",
        description:
          "Overview of the Lithos Client API. Lithos provides API calls to view information about mined blocks, miner reward payments, stratum parameters, and collateral utxos. Additionally, authentication allows for miners to create" +
          " collateral UTXOs which are crucial to continue mining on Lithos. In order to try out API calls, click on a specific request and use the bottom right panel to interact with the client.",
        slug: "/category/lithos-api"
      },
      items: require("./docs/lithosapi/sidebar.js")
    }
  ],
  startUpSidebar: [
    {type: "doc", id: "startup-intro"},
    { type: "autogenerated", dirName: "startup" },
  ],
};

export default sidebars;