import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "lithosapi/lithos-client-api",
    },
    {
      type: "category",
      label: "Info",
      description: "Information about the Lithos client and its current state",
      link: {
        type: "doc",
        id: "lithosapi/info",
      },
      items: [
        {
          type: "doc",
          id: "lithosapi/schemas/lithosinfo",
          label: "LithosInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/get-lithos-info",
          label: "Lithos client information",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Blocks",
      description: "Blocks currently being processed by Lithos contracts",
      link: {
        type: "doc",
        id: "lithosapi/blocks",
      },
      items: [
        {
          type: "doc",
          id: "lithosapi/schemas/poolblock",
          label: "PoolBlock",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/blockminers",
          label: "BlockMiners",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/get-contract-ids",
          label: "List UTXO ids for blocks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-blocks-by-height",
          label: "UTXO ids by block height",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-block-by-id",
          label: "Block info by UTXO id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-pool-blocks-by-ids",
          label: "Block info for multiple UTXO ids",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/get-block-miners-by-id",
          label: "Get a block's miner set",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-all-pool-blocks",
          label: "List all pool blocks",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Payments",
      description: "Payments made to you from Lithos contracts",
      link: {
        type: "doc",
        id: "lithosapi/payments",
      },
      items: [
        {
          type: "doc",
          id: "lithosapi/schemas/paymenttransaction",
          label: "PaymentTransaction",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/get-payments",
          label: "Get Lithos payouts",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Mining",
      description: "Information about the local stratum and mining process",
      link: {
        type: "doc",
        id: "lithosapi/mining",
      },
      items: [
        {
          type: "doc",
          id: "lithosapi/schemas/stratuminfo",
          label: "StratumInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/nisprepresentation",
          label: "NISPRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/get-stratum-info",
          label: "Get Stratum information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-best-nisp-at-height",
          label: "Get best NISP at height",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Statistics",
      description: "Mining, payment, collateral and client activity numbers for dashboards and graphs",
      link: {
        type: "doc",
        id: "lithosapi/stats",
      },
      items: [
        {
          type: "doc",
          id: "lithosapi/get-stats",
          label: "Statistics overview",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-mining-totals",
          label: "Mining and payment totals",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-mining-buckets",
          label: "Mining statistics by hour or day",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-mining-hashrate",
          label: "Estimate Lithos hashrate",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-difficulty-epochs",
          label: "Network difficulty by epoch",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-local-mining-summary",
          label: "This client's own hashrate",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-local-mining-history",
          label: "This client's hashrate over time",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-mining-payments",
          label: "This client's payouts and claims",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-collateral-stats",
          label: "Collateral inventory",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-local-mining-stats",
          label: "Local mining activity",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Collateral Market",
      description: "Stats and participation for the collateral market: the queue, the active set, emission state, and joining",
      link: {
        type: "doc",
        id: "lithosapi/collateral-market",
      },
      items: [
        {
          type: "doc",
          id: "lithosapi/schemas/collateralmarketinfo",
          label: "CollateralMarketInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/collateralqueueentry",
          label: "CollateralQueueEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/collateralactiveentry",
          label: "CollateralActiveEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/collateralpermithistorypoint",
          label: "CollateralPermitHistoryPoint",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/collateralpermithistory",
          label: "CollateralPermitHistory",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/collaterallenderkeystatus",
          label: "CollateralLenderKeyStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/collateralpositionsummary",
          label: "CollateralPositionSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/collateralrewardsummary",
          label: "CollateralRewardSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/collateralrewardclaimedchunk",
          label: "CollateralRewardClaimedChunk",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/collateralrewardclaimresult",
          label: "CollateralRewardClaimResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/walletcollateralstatus",
          label: "WalletCollateralStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/collateraljoincheckrequest",
          label: "CollateralJoinCheckRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/collateraljoinquote",
          label: "CollateralJoinQuote",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/collateraljoinexecuterequest",
          label: "CollateralJoinExecuteRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/collateraljoinentry",
          label: "CollateralJoinEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/collateraljoinresult",
          label: "CollateralJoinResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/get-collateral-market-info",
          label: "Collateral market snapshot",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-collateral-queue",
          label: "List queue boxes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-collateral-active-set",
          label: "List the active set",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-collateral-permit-history",
          label: "Permit price history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-collateral-reward-summary",
          label: "Your locked block rewards",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/claim-collateral-rewards",
          label: "Claim unlocked block rewards",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/check-collateral-join",
          label: "Quote joining the queue",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/join-collateral-queue",
          label: "Join the collateral queue",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Wallet",
      description: "Balances and lending status for the client's own wallet",
      link: {
        type: "doc",
        id: "lithosapi/wallet",
      },
      items: [
        {
          type: "doc",
          id: "lithosapi/schemas/walletbalances",
          label: "WalletBalances",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/get-wallet-balances",
          label: "Wallet balances and lending status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Lithos Dex",
      description: "Swap, provide liquidity, and collect permanent fees on the LithosDex pool",
      link: {
        type: "doc",
        id: "lithosapi/lithosdex",
      },
      items: [
        {
          type: "doc",
          id: "lithosapi/schemas/ldstatechangedresponse",
          label: "LDStateChangedResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldfeeparams",
          label: "LDFeeParams",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldpoolinfo",
          label: "LDPoolInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldvaultinfo",
          label: "LDVaultInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldswaprequest",
          label: "LDSwapRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldswapexecuterequest",
          label: "LDSwapExecuteRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldswapoutputrequest",
          label: "LDSwapOutputRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldswapquote",
          label: "LDSwapQuote",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldswapresult",
          label: "LDSwapResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/lddepositrequest",
          label: "LDDepositRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/lddepositexecuterequest",
          label: "LDDepositExecuteRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/lddepositquote",
          label: "LDDepositQuote",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/lddepositresult",
          label: "LDDepositResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldredeemrequest",
          label: "LDRedeemRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldredeemquote",
          label: "LDRedeemQuote",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldredeemresult",
          label: "LDRedeemResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldprovision",
          label: "LDProvision",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldprovisionlist",
          label: "LDProvisionList",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldclaimrequest",
          label: "LDClaimRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldclaimresult",
          label: "LDClaimResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldresizerequest",
          label: "LDResizeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldresizequote",
          label: "LDResizeQuote",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldresizeresult",
          label: "LDResizeResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldflushcheck",
          label: "LDFlushCheck",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldflushrequest",
          label: "LDFlushRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldflushresult",
          label: "LDFlushResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldswaporderrequest",
          label: "LDSwapOrderRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldswaporderexecuterequest",
          label: "LDSwapOrderExecuteRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldswaporderquote",
          label: "LDSwapOrderQuote",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/lddepositorderrequest",
          label: "LDDepositOrderRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/lddepositorderexecuterequest",
          label: "LDDepositOrderExecuteRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/lddepositorderquote",
          label: "LDDepositOrderQuote",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldredeemorderrequest",
          label: "LDRedeemOrderRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldredeemorderquote",
          label: "LDRedeemOrderQuote",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldorder",
          label: "LDOrder",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldorderlist",
          label: "LDOrderList",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldorderplacementresult",
          label: "LDOrderPlacementResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldtokenamount",
          label: "LDTokenAmount",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldordercancelresult",
          label: "LDOrderCancelResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldfeehistorypoint",
          label: "LDFeeHistoryPoint",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldfeehistory",
          label: "LDFeeHistory",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldprovisionfeehistory",
          label: "LDProvisionFeeHistory",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldpricepoint",
          label: "LDPricePoint",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldpricehistory",
          label: "LDPriceHistory",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldactivityentry",
          label: "LDActivityEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/ldrecentactivity",
          label: "LDRecentActivity",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/schemas/wallettoken",
          label: "WalletToken",
          className: "schema",
        },
        {
          type: "doc",
          id: "lithosapi/get-ld-pool",
          label: "LithosDex pool state",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-ld-vault",
          label: "LithosDex fee vault state",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/list-ld-orders",
          label: "List your outstanding orders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/check-ld-swap-order",
          label: "Quote a swap order",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/place-ld-swap-order",
          label: "Place a swap order",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/check-ld-deposit-order",
          label: "Quote a deposit order",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/place-ld-deposit-order",
          label: "Place a deposit order",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/check-ld-redeem-order",
          label: "Quote a redeem order",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/place-ld-redeem-order",
          label: "Place a redeem order",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/cancel-ld-order",
          label: "Cancel an order",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/check-ld-swap",
          label: "Quote a swap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/check-ld-swap-output",
          label: "Quote a swap by desired output",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/ld-swap",
          label: "Execute a swap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/check-ld-deposit",
          label: "Quote a liquidity deposit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/ld-deposit",
          label: "Deposit liquidity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/check-ld-redeem",
          label: "Quote a liquidity redemption",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/ld-redeem",
          label: "Redeem liquidity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/list-ld-provisions",
          label: "List liquidity provisions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/claim-ld-provision",
          label: "Claim settled fees for a provision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/check-ld-resize",
          label: "Quote a provision resize",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/ld-resize",
          label: "Resize a provision",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/check-ld-flush",
          label: "Check a pending fee flush",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/ld-flush",
          label: "Flush pending fees to the vault",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "lithosapi/get-ld-fee-history",
          label: "Pool-wide fee history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-ld-price-history",
          label: "Pool price history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-ld-recent-activity",
          label: "Recent pool activity",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "lithosapi/get-ld-provision-fee-history",
          label: "Fee history for one provision",
          className: "api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
